# Generated by Django 5.1.7 on 2025-03-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_assignment_max_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
